name: Build and Publish Minecraft Mod

on:
  push: # Kích hoạt khi có thay đổi mã nguồn trên mọi nhánh
  workflow_dispatch: # Hỗ trợ kích hoạt thủ công

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Cần để upload release asset
      packages: write # Cần nếu publish lên GitHub Packages

    steps:
    # Checkout mã nguồn
    - uses: actions/checkout@v4

    # Cài đặt JDK 21 (phù hợp với Minecraft 1.21+)
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Thêm quyền thực thi cho gradlew
    - name: Make gradlew executable
      run: chmod +x gradlew

    # Cài đặt Gradle
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    # Build mod với Gradle, sử dụng --build-cache
    - name: Build with Gradle
      run: ./gradlew build --build-cache

    # Lấy phiên bản từ gradle.properties
    - name: Get Mod Version
      id: get-version
      run: |
        VERSION=$(grep "mod_version" gradle.properties | cut -d'=' -f2)
        echo "mod_version=$VERSION" >> $GITHUB_OUTPUT
      shell: bash

    # Tạo release và upload file JAR
    - name: Create Release and Upload JAR
      id: create-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Lấy thời gian build (định dạng: YYYYMMDD-HHMMSS)
        BUILD_TIME=$(date -u +"%Y%m%d-%H%M%S")
        
        # Đường dẫn file JAR
        JAR_PATH="./build/libs/fly-mod-${{ steps.get-version.outputs.mod_version }}.jar"
        
        # Tên file upload bao gồm thời gian build
        JAR_NAME="fly-mod-${{ steps.get-version.outputs.mod_version }}-$BUILD_TIME.jar"
        
        # Tạo release với tag dựa trên phiên bản
        TAG_NAME="v${{ steps.get-version.outputs.mod_version }}-$BUILD_TIME"
        gh release create "$TAG_NAME" --title "Release $TAG_NAME" --notes "Auto-generated release for fly-mod version ${{ steps.get-version.outputs.mod_version }} built at $BUILD_TIME UTC" "$JAR_PATH" -R ${{ github.repository }} --target ${{ github.sha }}
        
        echo "release_tag=$TAG_NAME" >> $GITHUB_OUTPUT
        echo "jar_name=$JAR_NAME" >> $GITHUB_OUTPUT
      shell: bash

    # Xác nhận upload (tùy chọn, để debug)
    - name: Verify Upload
      run: |
        echo "Uploaded JAR: ${{ steps.create-release.outputs.jar_name }}"
        echo "Release Tag: ${{ steps.create-release.outputs.release_tag }}"
